### 주문 생성
POST http://localhost:8080/orders
Content-Type: application/json

{
  "userId": 1,
  "requests": [
    {
      "productId":1,
      "quantity": 1
    }
  ]
}

### 전체 주문 목록 조회
GET http://localhost:8080/orders

### 주문 금액 변경
PATCH http://localhost:8080/orders/1/orderItems/1/price?price=3000
Content-Type: application/json


### 주문 수량 변경
PATCH http://localhost:8080/orders/1/orderItems/1/quantity?quantity=100
Content-Type: application/json
